service: miranda-backend
frameworkVersion: "3"
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
    - "data/**"
    - "public/**"
provider:
  name: aws
  region: eu-west-3
  runtime: nodejs18.x
  httpApi:
    cors:
      allowedOrigins:
        - "http://miranda-frontend.s3-website.eu-west-3.amazonaws.com"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: true
  environment:
      SECRET_KEY: ${env:SECRET_KEY}
      MONGO_URI: ${env:MONGO_URI}

functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true



